---
name: bosh

releases:
  - name: bosh
    url: https://bosh.io/d/github.com/cloudfoundry/bosh?v=257.3
    sha1: e4442afcc64123e11f2b33cc2be799a0b59207d0
  - name: bosh-google-cpi
    url: https://storage.googleapis.com/bosh-cpi-artifacts/bosh-google-cpi-21.tgz
    sha1: 1bda4007a22147a700257655d64b38f6b4c5c0f1
  - name: uaa
    url: https://bosh.io/d/github.com/cloudfoundry/uaa-release?v=12.2
    sha1: 899f1e10f27e82ac524f1158a513392bbfabf2a0

resource_pools:
  - name: vms
    network: private
    stemcell:
      url: https://storage.googleapis.com/bosh-cpi-artifacts/light-bosh-stemcell-3262.2-google-kvm-ubuntu-trusty-go_agent.tgz
      sha1: f46d82a6ae6e89a5635cb3122389f0c8459a82e0 
    cloud_properties:
      machine_type: n1-standard-4
      root_disk_size_gb: 50
      root_disk_type: pd-standard
      service_scopes:
        - compute
        - devstorage.full_control

disk_pools:
  - name: disks
    disk_size: 32_768
    cloud_properties:
      type: pd-standard

networks:
  - name: vip
    type: vip
  - name: private
    type: manual
    subnets:
    - range: 10.0.0.0/24
      gateway: 10.0.0.1
      static: [10.0.0.3-10.0.0.7]
      cloud_properties:
        network_name: c0-run1-vnet
        subnetwork_name: c0-run1-subnet-bosh-us-east1
        ephemeral_external_ip: false
        tags:
          - nat-traverse
          - no-ip

jobs:
  - name: bosh
    instances: 1

    templates:
      - name: nats
        release: bosh
      - name: postgres
        release: bosh
      - name: powerdns
        release: bosh
      - name: blobstore
        release: bosh
      - name: director
        release: bosh
      - name: health_monitor
        release: bosh
      - name: google_cpi
        release: bosh-google-cpi

    resource_pool: vms
    persistent_disk_pool: disks

    networks:
      - name: private
        static_ips: [10.0.0.4]
        default:
          - dns
          - gateway

    properties:
      nats:
        address: 127.0.0.1
        user: nats
        password: nats-password

      postgres: &db
        listen_address: 127.0.0.1
        host: 127.0.0.1
        user: postgres
        password: postgres-password
        database: bosh
        adapter: postgres

      dns:
        address: 10.0.0.4
        domain_name: microbosh
        db: *db
        recursor: 169.254.169.254

      blobstore:
        address: 10.0.0.4
        port: 25250
        provider: dav
        director:
          user: director
          password: director-password
        agent:
          user: agent
          password: agent-password

      director:
        address: 127.0.0.1
        name: bosh-gcp
        db: *db
        cpi_job: google_cpi
        user_management:
        provider: local
        local:
          users:
          - {name: admin, password: admin}
          - {name: hm, password: hm-password}

      hm:
        director_account:
          user: hm
          password: hm-password
        resurrector_enabled: true

      google: &google_properties
        project: google.com:pcf-demos
        default_zone: us-east1-d

      agent:
        mbus: nats://nats:nats-password@10.0.0.4:4222
        ntp: *ntp
        blobstore:
           options:
             endpoint: http://10.0.0.4:25250
             user: agent
             password: agent-password

      ntp: &ntp
        - 169.254.169.254

cloud_provider:
  template:
    name: google_cpi
    release: bosh-google-cpi

  ssh_tunnel:
    host: 10.0.0.4
    port: 22
    user: bosh
    private_key: ~/.ssh/bosh

  mbus: https://mbus:mbus-password@10.0.0.4:6868

  properties:
    google: *google_properties
    agent:
      mbus: https://mbus:mbus-password@0.0.0.0:6868
      blobstore:
        provider: local
        options:
          blobstore_path: /var/vcap/micro_bosh/data/cache
      ntp: *ntp
