azs:
- name: z1
  cloud_properties:
    availability_zone: us-east1-c
- name: z2
  cloud_properties:
    availability_zone: us-east1-d

vm_types:
- name: medium
  cloud_properties:
    machine_type: n1-standard-1
    root_disk_size_gb: 30
    root_disk_type: pd-standard
- name: cell
  cloud_properties:
    machine_type: n1-highmem-4
    root_disk_size_gb: 50
    root_disk_type: pd-standard
- name: large
  cloud_properties:
    machine_type: n1-highcpu-4
    root_disk_size_gb: 30
    root_disk_type: pd-standard
- name: diego_access
  cloud_properties:
    machine_type: n1-standard-1
    root_disk_size_gb: 30
    root_disk_type: pd-standard
    target_pool: dwallraff-pcf-public-ssh
    tags:
      - pcf-public-ssh
- name: concourse-public
  cloud_properties:
    machine_type: n1-standard-4
    root_disk_size_gb: 30
    root_disk_type: pd-standard
    target_pool: dwallraff-concourse-public
    tags:
      - concourse-public
- name: pcf-public
  cloud_properties:
    machine_type: n1-standard-4
    root_disk_size_gb: 30
    root_disk_type: pd-standard
    target_pool: dwallraff-pcf-public
    tags:
      - pcf-public

disk_types:
- name: small
  disk_size: 3000
  cloud_properties:
    root_disk_size_gb: 3
    root_disk_type: pd-standard
- name: large
  disk_size: 50_000
  cloud_properties:
    root_disk_size_gb: 50
    root_disk_type: pd-standard

networks:
- name: bosh
  type: manual
  subnets:
  - range: 10.0.0.0/26
    gateway: 10.0.0.1
    az: z1
    static:
    - 10.0.0.4
    - 10.0.0.10
    reserved:
    - 10.0.0.1-10.0.0.2
    - 10.0.0.60-10.0.0.63
    dns: [169.254.169.254, 8.8.8.8]
    cloud_properties:
      network_name: dwallraff-vnet
      subnetwork_name: dwallraff-subnet-bosh-us-east1
      tags:
      - nat-traverse
      - no-ip
- name: concourse
  type: manual
  subnets:
  - range: 10.0.0.64/26
    gateway: 10.0.0.65
    az: z1
    static:
    - 10.0.0.72
    - 10.0.0.73
    - 10.0.0.74
    - 10.0.0.75
    reserved:
    - 10.0.0.65-10.0.0.70
    - 10.0.0.122-10.0.0.127
    dns: [169.254.169.254, 8.8.8.8]
    cloud_properties:
      network_name: dwallraff-vnet
      subnetwork_name: dwallraff-subnet-concourse-us-east1-c
      tags:
      - nat-traverse
      - no-ip
- name: pcf-z1
  type: manual
  subnets:
  - range: 10.0.4.0/22
    gateway: 10.0.4.1
    az: z1
    static:
    - 10.0.4.6-10.0.4.11
    reserved:
    - 10.0.4.1-10.0.4.5
    - 10.0.7.250-10.0.7.255
    dns: [169.254.169.254, 8.8.8.8]
    cloud_properties:
      network_name: dwallraff-vnet
      subnetwork_name: dwallraff-subnet-pcf-us-east1-c
      tags:
      - nat-traverse
      - no-ip
- name: pcf-z2
  type: manual
  subnets:
  - range: 10.0.8.0/22
    gateway: 10.0.8.1
    az: z2
    static:
    - 10.0.8.6-10.0.8.11
    reserved:
    - 10.0.8.1-10.0.8.5
    - 10.0.11.250-10.0.11.255
    dns: [169.254.169.254, 8.8.8.8]
    cloud_properties:
      network_name: dwallraff-vnet
      subnetwork_name: dwallraff-subnet-pcf-us-east1-d
      tags:
      - nat-traverse
      - no-ip
- name: public
  type: vip

compilation:
  workers: 5
  reuse_compilation_vms: true
  az: z1
  vm_type: medium
  network: pcf-z1