azs:
- name: z1
  cloud_properties:
    availability_zone: us-east1-c

vm_types:
- name: medium
  cloud_properties:
    machine_type: n1-standard-1
    root_disk_size_gb: 30
    root_disk_type: pd-standard
- name: cell
  cloud_properties:
    machine_type: n1-highmem-4
    root_disk_size_gb: 50
    root_disk_type: pd-standard
- name: large
  cloud_properties:
    machine_type: n1-highcpu-4
    root_disk_size_gb: 30
    root_disk_type: pd-standard
- name: diego_access
  cloud_properties:
    machine_type: n1-standard-1
    root_disk_size_gb: 30
    root_disk_type: pd-standard
    target_pool: diego-ssh-target-pool
- name: router
  cloud_properties:
    machine_type: n1-highcpu-4
    root_disk_size_gb: 30
    root_disk_type: pd-standard
    target_pool: cfrouter-target-pool
- name: concourse-public
  cloud_properties:
    machine_type: n1-standard-4
    root_disk_size_gb: 30
    root_disk_type: pd-standard
    target_pool: concourse-public
- name: cf-public
  cloud_properties:
    machine_type: n1-standard-4
    root_disk_size_gb: 30
    root_disk_type: pd-standard
    target_pool: cf-public

disk_types:
- name: small
  disk_size: 3000
  cloud_properties:
    root_disk_size_gb: 3
    root_disk_type: pd-standard
- name: large
  disk_size: 50_000
  cloud_properties:
    root_disk_size_gb: 50
    root_disk_type: pd-standard

networks:
- name: cf-public
  type: manual
  subnets:
  - range: 10.0.15.0/24
    gateway: 10.0.15.1
    az: z1
    static:
    - 10.0.15.12-10.0.15.17
    reserved:
    - 10.0.15.254-10.0.15.255
    - 10.0.15.1-10.0.15.5
    dns: [169.254.169.254, 8.8.8.8]
    cloud_properties:
      network_name: vnet
      subnetwork_name: cf-public
      tags:
      - nat-traverse
      - cf-public
- name: cf-private
  type: manual
  subnets:
  - range: 10.0.16.0/22
    gateway: 10.0.16.1
    az: z1
    static:
    - 10.0.16.12-10.0.16.17
    reserved:
    - 10.0.16.254-10.0.16.255
    - 10.0.16.1-10.0.16.5
    dns: [169.254.169.254, 8.8.8.8]
    cloud_properties:
      network_name: vnet
      subnetwork_name: cf-private
      tags:
      - nat-traverse
- name: concourse-public
  type: manual
  subnets:
  - range: 10.0.3.0/24
    gateway: 10.0.3.1
    az: z1
    static:
    - 10.0.3.12-10.0.3.17
    reserved:
    - 10.0.3.254-10.0.3.255
    - 10.0.3.1-10.0.3.6
    dns: [169.254.169.254, 8.8.8.8]
    cloud_properties:
      network_name: vnet
      subnetwork_name: concourse-public
      tags:
      - nat-traverse
      - concourse-public
- name: concourse-private
  type: manual
  subnets:
  - range: 10.0.2.0/24
    gateway: 10.0.2.1
    az: z1
    static:
    - 10.0.2.12-10.0.2.17
    reserved:
    - 10.0.2.254-10.0.2.255
    - 10.0.2.1-10.0.2.6
    dns: [169.254.169.254, 8.8.8.8]
    cloud_properties:
      network_name: vnet
      subnetwork_name: concourse-private
      tags:
      - nat-traverse
      - concourse-private
- name: public
  type: vip

compilation:
  workers: 5
  reuse_compilation_vms: true
  az: z1
  vm_type: medium
  network: cf-private