azs:
- name: z1
  cloud_properties:
    availability_zone: us-east1-c
- name: z2
  cloud_properties:
    availability_zone: us-east1-d

vm_types:
- name: medium
  cloud_properties:
    machine_type: n1-standard-1
    root_disk_size_gb: 30
    root_disk_type: pd-standard
- name: cell
  cloud_properties:
    machine_type: n1-highmem-4
    root_disk_size_gb: 50
    root_disk_type: pd-standard
- name: large
  cloud_properties:
    machine_type: n1-highcpu-4
    root_disk_size_gb: 30
    root_disk_type: pd-standard
- name: diego_access
  cloud_properties:
    machine_type: n1-standard-1
    root_disk_size_gb: 30
    root_disk_type: pd-standard
    target_pool: diego-ssh-target-pool
- name: router
  cloud_properties:
    machine_type: n1-highcpu-4
    root_disk_size_gb: 30
    root_disk_type: pd-standard
    target_pool: cfrouter-target-pool
- name: concourse-public
  cloud_properties:
    machine_type: n1-standard-4
    root_disk_size_gb: 30
    root_disk_type: pd-standard
    target_pool: c0-run1-concourse-public
- name: pcf-public
  cloud_properties:
    machine_type: n1-standard-4
    root_disk_size_gb: 30
    root_disk_type: pd-standard
    target_pool: c0-run1-pcf-public

disk_types:
- name: small
  disk_size: 3000
  cloud_properties:
    root_disk_size_gb: 3
    root_disk_type: pd-standard
- name: large
  disk_size: 50_000
  cloud_properties:
    root_disk_size_gb: 50
    root_disk_type: pd-standard

networks:
- name: bosh
  type: manual
  subnets:
  - range: 10.0.0.0/26
    gateway: 10.0.0.1
    az: z1
    static:
    - 10.0.0.4
    - 10.0.0.10
    reserved:
    - 10.0.0.1-10.0.0.2
    - 10.0.0.60-10.0.0.63
    dns: [169.254.169.254, 8.8.8.8]
    cloud_properties:
      network_name: c0-run1-vnet
      subnetwork_name: c0-run1-subnet-bosh-us-east1
      tags:
      - nat-traverse
      - no-ip
- name: pcf-public-z1
  type: manual
  subnets:
  - range: 10.0.1.0/24
    gateway: 10.0.1.1
    az: z1
    static:
    - 10.0.1.6-10.0.1.11
    reserved:
    - 10.0.1.1-10.0.1.5
    - 10.0.1.250-10.0.1.255
    dns: [169.254.169.254, 8.8.8.8]
    cloud_properties:
      network_name: c0-run1-vnet
      subnetwork_name: c0-run1-subnet-pcf-public-us-east1-c
      tags:
      - nat-traverse
      - pcf-public
      - no-ip
- name: pcf-private-z1
  type: manual
  subnets:
  - range: 10.0.2.0/23
    gateway: 10.0.2.1
    az: z1
    static:
    - 10.0.2.7-10.0.2.27
    reserved:
    - 10.0.2.1-10.0.2.5
    - 10.0.3.250-10.0.3.255
    dns: [169.254.169.254, 8.8.8.8]
    cloud_properties:
      network_name: c0-run1-vnet
      subnetwork_name: c0-run1-subnet-pcf-private-us-east1-c
      tags:
      - nat-traverse
      - no-ip
- name: pcf-public-z2
  type: manual
  subnets:
  - range: 10.0.6.0/24
    gateway: 10.0.6.1
    az: z2
    static:
    - 10.0.6.6-10.0.6.11
    reserved:
    - 10.0.6.1-10.0.6.5
    - 10.0.6.250-10.0.6.255
    dns: [169.254.169.254, 8.8.8.8]
    cloud_properties:
      network_name: c0-run1-vnet
      subnetwork_name: c0-run1-subnet-pcf-public-us-east1-d
      tags:
      - nat-traverse
      - pcf-public
      - no-ip
- name: pcf-private-z2
  type: manual
  subnets:
  - range: 10.0.4.0/23
    gateway: 10.0.4.1
    az: z2
    static:
    - 10.0.4.7-10.0.4.27
    reserved:
    - 10.0.4.1-10.0.4.5
    - 10.0.5.250-10.0.5.255
    dns: [169.254.169.254, 8.8.8.8]
    cloud_properties:
      network_name: c0-run1-vnet
      subnetwork_name: c0-run1-subnet-pcf-private-us-east1-d
      tags:
      - nat-traverse
      - no-ip
- name: concourse-public
  type: manual
  subnets:
  - range: 10.0.0.64/26
    gateway: 10.0.0.65
    az: z1
    static:
    - 10.0.0.72
    reserved:
    - 10.0.0.65-10.0.0.70
    - 10.0.0.122-10.0.0.127
    dns: [169.254.169.254, 8.8.8.8]
    cloud_properties:
      network_name: c0-run1-vnet
      subnetwork_name: c0-run1-subnet-concourse-public-us-east1-c
      tags:
      - nat-traverse
      - concourse-public
      - no-ip
- name: concourse-private
  type: manual
  subnets:
  - range: 10.0.0.128/25
    gateway: 10.0.0.129
    az: z1
    static:
    - 10.0.0.134
    - 10.0.0.135
    - 10.0.0.136
    reserved:
    - 10.0.0.129-10.0.0.133
    - 10.0.0.250-10.0.0.255
    dns: [169.254.169.254, 8.8.8.8]
    cloud_properties:
      network_name: c0-run1-vnet
      subnetwork_name: c0-run1-subnet-concourse-private-us-east1-c
      tags:
      - nat-traverse
      - concourse-private
      - no-ip
- name: public
  type: vip

compilation:
  workers: 5
  reuse_compilation_vms: true
  az: z1
  vm_type: medium
  network: pcf-private-z1